os: linux
language: java
jdk:
  - openjdk11
dist: xenial

addons:
  chrome: stable
env:
  - NODE_VERSION="12.14.0"
before_install:
  - nvm install $NODE_VERSION
install:
  - rm -rf node_modules
script: sh ./.travis.script.sh
